calculation/urls.py
from django.conf.urls import url
from . import views

app_name = 'calculation'

urlpatterns = [
    # GENERAL URLS
    url(r'^$', views.home_view, name='home'),
    url(r'^about/$', views.about_view, name='about'),
    url(r'^help/$', views.help_view, name='help'),
    url(r'^terms/$', views.terms_view, name='terms'),
    url(r'^privacy/$', views.privacy_view, name='privacy'),
    url(r'^message-board/$', views.message_board_view, name='message'),
    # CALCULATION URLS
    url(r'^calculation/(?P<category_slug>[-\w]+)/$', views.category_view, name='category'),
    url(r'^calculation/(?P<category_slug>[-\w]+)/(?P<calculation_slug>[-\w]+)/$', views.calculation_view,
        name='calculation'),
    # API URLS
    url(r'^api/posts/$', views.APIRoutePosts.as_view(), name='api_posts'),
    url(r'^api/calculation/(?P<category_slug>[-\w]+)/$', views.APIRouteCategory.as_view(), name='api_category'),
    url(r'^api/calculation/(?P<category_slug>[-\w]+)/(?P<calculation_slug>[-\w]+)/$',
        views.APIRouteCalculation.as_view(), name='api_calculation'),
]

mathfever/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^', include('calculation.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'calculation.views.page_not_found_view'
handler500 = 'calculation.views.server_error_view'

calculation/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django_mysql.models import ListTextField

STATUS_CHOICES = (
    ('d', 'Draft'),
    ('p', 'Published'),
)

INPUT_TYPE_CHOICES = (
    ('binary_str', 'Binary String'),
    ('integer_str', 'Integer String'),
    ('decimal_Decimal', 'Decimal decimal.Decimal'),
    ('decimal_int', 'Decimal Integer'),
    ('hexadecimal_str', 'Hexadecimal String'),
)


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, editable=False)
    image = models.ImageField(upload_to="images/category-cards")
    body = models.TextField(blank=True)
    meta = models.TextField(blank=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('calculation:category', args=[self.slug])


class Calculation(models.Model):
    category = models.ForeignKey('Category', related_name='calculations')
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, editable=False)
    input_labels = ListTextField(base_field=models.CharField(max_length=500))
    input_ids = ListTextField(base_field=models.CharField(max_length=500))
    input_type = models.CharField(max_length=100, choices=INPUT_TYPE_CHOICES)
    function = models.CharField(max_length=100)
    meta = models.TextField(blank=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Calculation, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('calculation:calculation', args=[self.category.slug, self.slug])

    def get_api_networking_absolute_url(self):
        return reverse('calculation:networking', args=[self.slug])


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, editable=False)
    body = models.TextField()
    image = models.ImageField(upload_to="images/posts")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # On save, update timestamps
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)

calculation/views.py
from collections import OrderedDict
from decimal import Decimal

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from rest_framework.decorators import APIView
from rest_framework.views import Response

import calculation.mathematics.networking as networking
import calculation.mathematics.numbers as numbers
import calculation.mathematics.percentages as percentages
import calculation.mathematics.total_surface_area as tsa
from calculation.mathematics.validation import binary_validation, decimal_validation, hexadecimal_validation
from calculation.models import Category, Calculation, Post
from calculation.serializers import PostSerializer, CalculationSerializer, CategorySerializer


#################
# GENERAL VIEWS #
#################
def home_view(request):
    categories = Category.objects.all()
    meta = 'MathFever - A website where users can find mathematical proof and answers to common math problems, with ' \
           'values of their choosing.'
    return render(request, 'calculation/home.html', {'title': 'Home', 'categories': categories, 'meta': meta})


def about_view(request):
    return render(request, 'calculation/general/about.html', {'title': 'About'})


def help_view(request):
    return render(request, 'calculation/general/help.html', {'title': 'Help'})


def terms_view(request):
    return render(request, 'calculation/general/terms.html', {'title': 'Terms of Use'})


def privacy_view(request):
    return render(request, 'calculation/general/privacy.html', {'title': 'Privacy'})


def message_board_view(request):
    post_list = Post.objects.filter(status='p').order_by('-created')
    paginator = Paginator(post_list, 2)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        page = '1'
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'calculation/message.html', {'title': 'Message Board', 'posts': posts, 'page': page})


def category_view(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    meta = category.meta
    return render(request, 'calculation/general/category.html', {'title': category.title, 'category': category,
                                                                 'meta': meta})


def calculation_view(request, category_slug, calculation_slug):
    calculation = get_object_or_404(Calculation, category__slug=category_slug, slug=calculation_slug)
    category = calculation.category
    meta = calculation.meta

    input_ids = calculation.input_ids
    input_labels = calculation.input_labels
    form = zip(input_ids, input_labels)
    return render(request, 'calculation/calculation.html', {'title': calculation.title, 'form_name': calculation.slug,
                                                            'form': form, 'meta': meta, 'category': category})


#############
# API VIEWS #
#############
class APIRoutePosts(APIView):
    @staticmethod
    def get(request):
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)


class APIRouteCategory(APIView):
    @staticmethod
    def get(request, category_slug):
        category = get_object_or_404(Category, slug=category_slug)
        serializer = CategorySerializer(category)
        return Response(serializer.data)


class APIRouteCalculation(APIView):
    @staticmethod
    def get(request, category_slug, calculation_slug):
        calculation = get_object_or_404(Calculation, category__slug=category_slug, slug=calculation_slug)
        serializer = CalculationSerializer(calculation)
        return Response(serializer.data)

    @staticmethod
    def post(request, category_slug, calculation_slug):
        calculation = get_object_or_404(Calculation, category__slug=category_slug, slug=calculation_slug)
        return APIHandler.process_api_request(request, eval(calculation.function), calculation.input_ids,
                                              calculation.input_type)


class APIHandler:
    """
    Called by APIRouteCalculation view via a post request. Its methods handle request.data and calling math function,
    returning a response of {'content': <str>}.
    """

    @staticmethod
    def process_api_request(request, math_function, accepted_arguments, input_type):
        """
        This method is used to process an api request. It handles the retrieval of data from request.data of param
        accepted_arguments. Then depending upon input_type it validates the data and responds with a json object.

        :param request: From rest_framework.request.Request
        :type request: rest_framework.request.Request
        :param math_function: The math function that needs to be used to the API route
        :type math_function: function
        :param accepted_arguments: The accepted arguments for the API route
        :type accepted_arguments: tuple(str)
        :param input_type: The type of input required for the function from param math_function
        :type input_type: str
        :return: Return a Response of json object with attribute of either 'content or 'error'
        :rtype: rest_framework.response.Response
        """
        request_data = OrderedDict()
        try:
            for argument in accepted_arguments:
                request_data[argument] = request.data[argument].replace(' ', '')
        except KeyError:
            return Response({'error': APIHandler.invalid_args(accepted_arguments)}, status=403)
        else:
            # binary input, and math function param requires str
            if input_type == 'binary_str':
                if binary_validation(request_data):
                    return Response({'content': math_function(*request_data.values())})
                else:
                    return Response({'error': APIHandler.invalid_input_length_limit('binary string')}, status=403)

            # hexadecimal input, and math function param requires str
            elif input_type == 'hexadecimal_str':
                if hexadecimal_validation(request_data):
                    return Response({'content': math_function(*request_data.values())})
                else:
                    return Response({'error': APIHandler.invalid_input_length_limit('hexadecimal')}, status=403)

            # whole number input, and math function param requires str
            elif input_type == 'integer_str':
                if decimal_validation(request_data):
                    try:
                        for argument in accepted_arguments:
                            request_data[argument] = str(int(request_data[argument]))
                    except ValueError:
                        return Response({'error': APIHandler.invalid_input_number_limit('whole number')}, status=403)
                    else:
                        return Response({'content': math_function(*request_data.values())})

                else:
                    return Response({'error': APIHandler.invalid_input_number_limit('whole number')}, status=403)

            # whole number input, and math function param requires int
            elif input_type == 'decimal_int':
                try:
                    for argument in accepted_arguments:
                        request_data[argument] = int(request_data[argument])
                except ValueError:
                    return Response({'error': APIHandler.invalid_input_number_limit('whole number')}, status=403)
                else:
                    return Response({'content': math_function(*request_data.values())})

            # number input, and math function param requires decimal.Decimal
            elif input_type == 'decimal_Decimal':
                try:
                    for argument in accepted_arguments:
                        request_data[argument] = tsa.normalize_quantize(Decimal(request_data[argument]))
                except ValueError:
                    return Response({'error': APIHandler.invalid_input_number_limit('decimal')}, status=403)
                else:
                    return Response({'content': math_function(*request_data.values())})
            else:
                raise Exception("Argument input_type is incorrect.")

    @staticmethod
    def invalid_args(args):
        return '<p>Invalid arguments. This API route accepts the following arguments: {args}.</p>'.format(args=args)

    @staticmethod
    def invalid_input_length_limit(valid_type):
        return '<p>User input is invalid, please enter only {valid_type} values. Must not be over 64 characters in ' \
               'length.</p>'.format(valid_type=valid_type)

    @staticmethod
    def invalid_input_number_limit(valid_type):
        return '<p>User input is invalid, please enter only {valid_type} values. Must not be over 999,999,999,999.' \
               '</p>'.format(valid_type=valid_type)


###############
# ERROR VIEWS #
###############
def page_not_found_view(request):
    return render(request, 'calculation/error/404.html', {'title': 'Page not found'}, status=404)


def server_error_view(request):
    return render(request, 'calculation/error/500.html', {'title': 'Server Error'}, status=500)

calculation/templates/calculation/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="eng">

<!-- Head -->
<head>
    <!-- Title -->
    <title>{{ title }} - MathFever</title>

    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if meta %}
        <meta name="description" content="{{ meta }}"/>
    {% endif %}

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'calculation/images/favicon/favicon.ico' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-deep_orange.min.css"/>
    <link rel="stylesheet" href="{% static 'calculation/stylesheets/style.css' %}">

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-87666889-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<!-- Body -->
<body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base" onbeforeunload="">
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <!-- Header -->
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span id="top-bar-title" class="mdl-layout-title">MathFever</span>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" href="{% url 'calculation:home' %}">Home</a>
                <a class="mdl-navigation__link" href="{% url 'calculation:message' %}?page=1">Message Board</a>
                <a class="mdl-navigation__link" href="{% url 'calculation:about' %}">About</a>
                <a class="mdl-navigation__link" href="{% url 'calculation:help' %}">Help</a>
            </nav>
        </div>
    </header>

    <!-- Drawer -->
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">MathFever</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{% url 'calculation:home' %}">Home</a>
            <a class="mdl-navigation__link" href="{% url 'calculation:message' %}?page=1">Message Board</a>
            <a class="mdl-navigation__link" href="{% url 'calculation:about' %}">About</a>
            <a class="mdl-navigation__link" href="{% url 'calculation:help' %}">Help</a>
        </nav>
    </div>

    <!-- Main -->
    <main class="mdl-layout__content">
        <!-- Whole Content Excl Header/Drawer-->
        <div id="page-content">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer -->
        <footer class="mdl-mini-footer">
            <div class="mdl-mini-footer__left-section">
                <div class="small-caps mdl-logo">© 2016 MathFever.xyz</div>
                <ul class="mdl-mini-footer__link-list">
                    <li><a href="{% url 'calculation:help' %}">Help</a></li>
                    <li><a href="{% url 'calculation:terms' %}">Terms of Use</a></li>
                    <li><a href="{% url 'calculation:privacy' %}">Privacy</a></li>
                </ul>
            </div>
        </footer>
    </main>

</div>

<!-- JS -->
{% block scipts %}
{% endblock %}
<script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>

</body>

</html>

calculation/templates/calculation/calculation.html
{% extends 'calculation/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="calculation-page-heading">
        <!-- Main Heading -->
        <h3><a href="{{ category.get_absolute_url }}">{{ category }}:</a></h3>
        <h2 id="main-heading">{{ title }}</h2>
    </div>

    <!-- User Input Form -->
    <form id="calculation-form"> {% csrf_token %}

        {% for input_id, input_label in form %}
            <!-- User Input Field -->
            <div class="user-input-field mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" name="{{ input_id }}" type="text" id="{{ input_id }}"
                       autocomplete="off">
                <label class="mdl-textfield__label" for="{{ input_id }}"
                       id="{{ input_id }}Label">{{ input_label }}</label>
            </div>
        {% endfor %}

        <!-- Raised button with ripple -->
        <button type="submit"
                class="calculation-button mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
            Calculate
        </button>
    </form>

    <hr class="separator">

    <!-- Page Content-->
    <!-- Calculation Card -->
    <div class="mdl-grid">
        <div id="calculation-card" class="general-content mdl-color--white content mdl-color-text--grey-800 mdl-cell mdl-cell--10-col
        mdl-shadow--2dp">
        </div>
    </div>
{% endblock %}


{% block scipts %}
    <script src="{% static 'calculation/scripts/scripts.js' %}"></script>
    <script src="{% static 'calculation/scripts/form.js' %}"></script>
{% endblock %}

calculation/templates/calculation/home.html
{% extends 'calculation/base.html' %}
{% load static %}

{% block head-tile %}
    MathFever
{% endblock %}

{% block content %}
    <!-- Main Heading -->
    <h1 id="main-heading">{{ title }}</h1>
    <!-- Page Content-->
    <hr class="separator">

    <!-- Index of Categories -->
    <div class="mdl-grid">

        {% for category in categories %}
            <!-- Index Card -->
            <div class="home-card demo-card-wide mdl-card mdl-cell mdl-cell--top mdl-cell--4 mdl-cell--4-col-phone mdl-shadow--2dp">

                <!-- Index Card Picture/Title -->
                <div class="home-card--title mdl-card__title"
                     style="background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)),
                             url('{{ category.image.url }}') center / cover">
                    <h6 class="mdl-card__title-text">
                        <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                    </h6>
                </div>

                <!-- Index Card Text-->
                <div class="home-card--text mdl-card__supporting-text">
                    <ul>
                        {% for calculation in category.calculations.all %}
                            <li>
                                <a href="{{ calculation.get_absolute_url }}">{{ calculation.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
        {% endfor %}

    </div>
{% endblock %}

calculation/templates/calculation/message.html
{% extends 'calculation/base.html' %}

{% block content %}
    <!-- Main Heading -->
    <h1 id="main-heading">{{ title }}</h1>
    <hr class="separator">

    <!-- Page Content-->
    <div class="mdl-grid">
        <div class="general-content mdl-color--white content mdl-color-text--grey-800 mdl-cell mdl-cell--9-col
        mdl-shadow--2dp">

            {% for post in posts %}
                <div class="post">
                    <h3>{{ post.title }}</h3>
                    {{ post.body | safe }}
                    <p><strong>{{ post.created.date }}</strong></p>
                </div>
            {% endfor %}

            <div class="pagination">
                <span class="step-links">
                    {% if posts.has_previous %}
                        <a href="?page={{ posts.previous_page_number }}">Previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                    </span>

                    {% if posts.has_next %}
                        <a href="?page={{ posts.next_page_number }}">Next</a>
                    {% endif %}
                </span>
            </div>
        </div>
        {% if page == '1' %}
            <!-- Show Disqus -->
            <div id="disqus_thread" class="mdl-cell mdl-cell--8-col"></div>
            <script>
                /*
                 var disqus_config = function () {
                 this.page.url = location.href;
                 this.page.identifier = window.location.pathname;
                 };
                 */
                (function () { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = '//mathfever.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments
                powered by Disqus.</a></noscript>
        {% endif %}
    </div>
    <script id="dsq-count-scr" src="//mathfever.disqus.com/count.js" async></script>
{% endblock %}